apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ns77es89o-python
  janus-idp.io/tekton: ns77es89o-python
  backstage.io/kubernetes-id: ns77es89o-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ns77es89o-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
