apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ns77es89o-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ns77es89o-python 
  name: ns77es89o-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ns77es89o-python 
